dist: trusty
sudo: required

language: c
cache: ccache
git:
    submodules: false

os:
    - linux

compiler:
    - clang
    - gcc


before_script:
    - cd GmSSL
    - ./config

script:
    - $make

